# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: romero.ai
name: "cesar romero"
email: cesar.romero@gmail.com
description: >-
  personal site with information about tutoring and consulting
  services by cesar romero
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://romero.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: romerocesar
github_username:  romerocesar

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark # dark, neon, dirt, air, contrast, default
repository: romerocesar/romero.ai
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
